[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
itertools = "0.14.0"
clap = { version = "4.5.52", features = ["derive"] }
once_cell = "1.21.3"
